### PR TITLE
I dont wanna live anymore lol

### PR DESCRIPTION
**Pull request by ClaraCrazy**
Commands for editing & deleting messages and blacklisting users via ID

I didnt make a help command so make one yourself

its `(prefix)edit <MessageID> <new Message>` for editing
`(prefix)delete <MessageID>` for deleting
and `(prefix)blacklist <UserID>` for blacklisting a user

all done now. fully working chat with every feature embeds have to offer. 

sadly videos arent possible as discord doesnt allow them
So this project is now.... DONE

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
made some more changes... dont pull yet. updating later

**Comment by ClaraCrazy** [comment]
now you can pull xD

added help command... code is a pain in the ass to read bc I dont care about it... feel free to make it look good. you could probs. bring it down to 400 lines if you **really** wanted to lol. but I dont care

**Comment by strich3** [comment]
Error:

nst ownerID == "513369020####"
^^^^^^^

SyntaxError: Missing initializer in const declaration
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by bycop** [comment]
> Error:
> 
> nst ownerID == "513369020####"
> ������^^^^^^^
> 
> SyntaxError: Missing initializer in const declaration
> at wrapSafe (internal/modules/cjs/loader.js:979:16)
> at Module._compile (internal/modules/cjs/loader.js:1027:27)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> at Module.load (internal/modules/cjs/loader.js:928:32)
> at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
> at internal/main/run_main_module.js:17:47

Remove one "="

**Pull request merged**
